// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqvdikfcloiuxhhmapzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxdmRpa2ZjbG9pdXhoaG1hcHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MjQ5MzEsImV4cCI6MjA2NzAwMDkzMX0.QbTB2YiTQU2YgOfgrouHUaObMfmV7lIkUSk4h1kWnHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});